### PR TITLE
Add death XP Config

### PR DESCRIPTION
**Pull request by Mattzi**
The plan was to be able to remove xp from users when they are dying.
Tell me If I forgot anything, but its tested and works for us on our exiled server

### CODE REVIEW

**Comment by moddedmcplayer** [comment]
Contact me on Discord.

**Comment by Mattzi** [comment]
Looks good to me

**Comment by moddedmcplayer** [comment]
Will be part of 2.0.7

**Comment by Mattzi** [comment]
@moddedmcplayer there was an issue with double ev.Attacker being passed in the exiled event. We both made an oopsie there.
Will you fix that yourself or should I open another pull request

**Comment by moddedmcplayer** [comment]
> @moddedmcplayer there was an issue with double ev.Attacker being passed in the exiled event. We both made an oopsie there. Will you fix that yourself or should I open another pull request

Yep, fixed, thanks.

**Pull request merged**
